package com.example.got.model

import com.example.got.R

object FakeDataSource {
    val dummyCharacters = listOf(
        Character(1, "Eddard Stark", "Lord of Winterfell", "Sean Bean", "Male", "Stark", R.drawable.ned,"Lord Eddard Stark, also known as Ned Stark, was the head of House Stark, the Lord of Winterfell and Warden of the North, and later Hand of the King to King Robert I Baratheon. He was the older brother of Benjen, Lyanna and the younger brother of Brandon Stark. He is the father of Robb, Sansa, Arya, Bran, and Rickon by his wife, Catelyn Tully, and uncle of Jon Snow, who he raised as his bastard son. He was a dedicated husband and father, a loyal friend, and an honorable lord."),
        Character(2, "Catelyn Stark", "Cat", "Michelle Fairley", "Female", "Stark", R.drawable.catelyn,"Lady Catelyn Stark, née Tully, was born into House Tully as the daughter of Hoster Tully, the Lord Paramount of the Trident, and sister of Lysa and Edmure Tully. She was the wife of Eddard Stark and the mother of his five children."),
        Character(3, "Robb Stark", "The Wolf Pup", "Richard Madden", "Male", "Stark", R.drawable.robb,"Robb was the eldest child of Lady Catelyn and Lord Eddard Stark.[11] Robb was born at Riverrun and raised at Winterfell. His father left his mother the morning after their wedding to fight in Robert's Rebellion and did not return until after Robb was born. Robb Stark was likely named after Robert Baratheon.[citation needed] He had two younger trueborn brothers, Bran and Rickon, and two sisters, Sansa and Arya.[2]"),
        Character(4, "Sansa Stark", "Little bird", "Sophie Turner", "Female", "Stark", R.drawable.sansa,"Queen Sansa Stark is the eldest daughter of Lord Eddard Stark and his wife, Lady Catelyn, sister of Robb, Arya, Bran, and Rickon Stark, and \"half-sister\" of Jon Snow; though truthfully is his cousin. Initially betrothed to Prince Joffrey Baratheon, the heir to the Iron Throne, Sansa travels to King's Landing in preparation for her nuptials, but essentially becomes a hostage of House Lannister following the execution of her father on trumped-up charges of treason. Under the (sometimes unwitting) tutelage of Cersei Lannister, Margaery Tyrell, and Petyr Baelish, Sansa becomes well-versed in politics and court intrigue, but suffers all the same.") ,
        Character(5, "Arya Stark", "Many-Faced", "Maisie Williams", "Female", "Stark", R.drawable.arya,"Princess Arya Stark is the third child and second daughter of Lord Eddard Stark and his wife, Lady Catelyn Stark. She is the sister of the incumbent Westerosi monarchs, Sansa, Queen in the North, and Brandon, King of the Andals and the First Men. After narrowly escaping the persecution of House Stark by House Lannister, Arya is trained as a Faceless Man at the House of Black and White in Braavos, using her abilities to avenge her family. Upon her return to Westeros, she exacts retribution for the Red Wedding by exterminating the Frey male line."),
        Character(6, "Bran Stark", "The Three-Eyed Raven", "Isaac Hempstead Wright", "Male", "Stark", R.drawable.bran,"King Bran I the Broken, born Brandon Stark and commonly known simply as \"Bran,\" is the fourth child and second son of Eddard and Catelyn Stark. Bran is a warg and a greenseer serving as the new Three-Eyed Raven. Eventually, he was crowned as the first elected ruler of the Six Kingdoms, styled as Bran the Broken, the First of His Name, King of the Andals and the First Men, Lord of the Six Kingdoms, and Protector of the Realm."),

        Character(7, "Aerys II Targaryen", "The Mad King", "David Rintoul", "Male", "Targaryen", R.drawable.aerys,"King Aerys II Targaryen,[N 2] commonly called the Mad King, was the sixteenth member of House Targaryen to rule from the Iron Throne. Although his rule began benevolently, he succumbed to the madness caused by his incestuous lineage, and was eventually deposed by Lord Robert Baratheon in a civil war."),
        Character(8, "Rhaegar Targaryen", "The Last Dragon", "Wilf Scolding", "Male", "Targaryen", R.drawable.rhaegar,"Prince Rhaegar Targaryen, the last Prince of Dragonstone, was the eldest son and heir to King Aerys II Targaryen, the Mad King. He was the older brother of Viserys and Daenerys Targaryen and the husband of Elia Martell, with whom he had two children, Rhaenys and Aegon. He also fathered Jon Snow with Lyanna Stark, whom he secretly married following an annulment from Elia."),
        Character(9, "Viserys Targaryen", "The Dragon", "Harry Lloyd", "Male", "Targaryen", R.drawable.viserys,"Viserys Targaryen[N 4] was the younger brother of the late Rhaegar Targaryen, the older brother of Daenerys Targaryen and the uncle of Jon Snow. Viserys and Daenerys were the remnants of the exiled House Targaryen following a rebellion against their father, Aerys II Targaryen, the \"Mad King.\" He claimed the Iron Throne as King Viserys III following his father's murder, but never returned to Westeros, as he was killed by his brother-in-law, Khal Drogo, before he could make any attempt to take the throne."),
        Character(10, "Daenerys Targaryen", "The Dragon Queen", "Emilia Clarke", "Female", "Targaryen", R.drawable.daenerys,"Queen Daenerys I Targaryen,[N 2] also known as Daenerys Stormborn, and affectionately known as Dany, was the only daughter of King Aerys II Targaryen and Queen Rhaella, and the younger sister of Rhaegar and Viserys Targaryen. Daenerys was initially a timid, obedient youth. After her marriage to Drogo she gathered the confidence of his khalasar. Following his death, she expanded her dominion into Essos, gaining the loyalty of an army of Unsullied and liberating Slaver's Bay from the Ghiscari slave masters."),
        Character(11, "Jon Snow", "The Bastard of Winterfell", "Kit Harington", "Male", "Targaryen", R.drawable.jon,"Jon Snow, born Aegon Targaryen,[N 2] is the son of Lyanna Stark and Rhaegar Targaryen, the late Prince of Dragonstone. From infancy, Jon is presented as the bastard son of Lord Eddard Stark, Lyanna's brother, and raised alongside Eddard's lawful children at Winterfell. Jon's true parentage is kept secret from everyone, including Jon himself, in order to protect him from those that sought the complete annihilation of House Targaryen."),

        Character(12, "Robert Baratheon", "The Usurper", "Mark Addy", "Male", "Baratheon", R.drawable.robert,"King Robert I Baratheon was the seventeenth ruler of the Seven Kingdoms and the first king of the Baratheon dynasty Robert, a great warrior and charismatic man in his youth, took the throne through conquest in the war known as Robert's Rebellion, which began when the Prince of Dragonstone, Rhaegar Targaryen, allegedly abducted Robert's betrothed, Lyanna Stark. Killing Rhaegar at the Battle of the Trident, his climactic duel turned the tides of the war in his favor. After the war and following Lyanna's death, Robert married Cersei Lannister to cement an alliance with House Lannister to hold the kingdoms together, but he mistreated her and the marriage was loveless."),
        Character(13, "Stannis Baratheon", "Son of Fire", "Stephen Dillane", "Male", "Baratheon", R.drawable.stannis,"Stannis Baratheon was the Lord of Dragonstone, the younger brother of King Robert Baratheon, and older brother of Renly Baratheon. On account of the revelation of Robert's supposed children's true parentage, Stannis declares himself the rightful King after Robert's death as his rightful heir, and begins a campaign to take the Iron Throne. After assassinating his younger brother Renly using blood magic, due to Renly also having claimed the throne despite being the youngest brother, Stannis almost succeeds in taking King's Landing at the Battle of the Blackwater, but is ultimately repelled by the armies of Tywin Lannister and House Tyrell. "),
        Character(14, "Renly Baratheon", "King Highgarden", "Gethin Anthony", "Male", "Baratheon", R.drawable.renly,"Renly Baratheon was the youngest of the three brothers of House Baratheon and Lord of Storm's End. Following the deposition of House Targaryen, and subsequent ascension of his eldest brother, Robert, he was granted the title of Lord Paramount of the Stormlands, despite his youth. He also served as Master of Laws on Robert's Small Council, but abandoned the latter position when laying claim to the Iron Throne upon Robert's death."),
        Character(15, "Shireen Baratheon", "Son of Stannis", "Kerry Ingram", "Female", "Baratheon", R.drawable.shireen,"Shireen is the daughter of Stannis and Selyse Baratheon. Her father is the head of House Baratheon of Dragonstone and has declared himself King of the Andals and the First Men. Shireen is Stannis's only living daughter and therefore his heir presumptive. She had three older brothers, who were stillborn.[1] The left side of her face is scarred by greyscale, which she caught as an infant. Normally considered a death sentence, Stannis refused to give up on her and called in every healer he could find from both sides of the Narrow Sea to try to cure her, and through the combination of their efforts they managed to succeed, though the left side of her face was left permanently scarred.[2]"),
        Character(16, "Joffrey Baratheon", "The False King", "Jack Gleeson", "Male", "Baratheon", R.drawable.joffrey,"King Joffrey I Baratheon was the eighteenth king to rule from the Iron Throne and the second king of the Baratheon dynasty. Though believed by most to be the eldest son of King Robert Baratheon and Queen Cersei Lannister, Joffrey is actually a bastard born from Cersei's incestuous relationship with her twin brother Jaime Lannister. He is the older brother of Myrcella and Tommen Baratheon. Joffrey's reckless decision to execute Ned Stark on false charges of treason ignited the War of the Five Kings."),

        Character(17, "Tywin Lannister", "Protector of the Realm", "Charles Dance", "Male", "Lannister", R.drawable.tywin,"Tywin was the head of House Lannister, Lord of Casterly Rock, and Warden of the West. Despite the several recent Kings in King's Landing, Tywin was the real power in King's Landing. Tywin was among the richest and most powerful people in Westeros. He is a widower with three children, Jaime, Cersei, and Tyrion.[1] Casterly Rock, the Lannisters' ancestral seat of power, is located over a group of highly productive goldmines, which have provided the Lannisters with immense wealth and power over the years and led to the joke that Tywin \"shits gold.\"[2][3]. Tywin is the beloved son of Tytos Lannister."),
        Character(18, "Jaime Lannister", "Kingslayer", "Nikolaj Coster", "Male", "Lannister", R.drawable.jaime,"Ser Jaime Lannister was the elder son of Lord Tywin Lannister, younger twin brother of Queen Cersei Lannister, and older brother of Tyrion Lannister. He was involved in an incestuous relationship with Cersei, and unknown to most, he was the biological father of her three bastard children, Joffrey, Myrcella, and Tommen, as well as her unborn child. During Robert's Rebellion, Jaime killed Aerys Targaryen, earning the derogatory nickname \"Kingslayer.\" He was pardoned by Robert and allowed to serve in his Kingsguard. Following King Robert's death, he was appointed as the Lord Commander of the Kingsguard to his son, Joffrey."),
        Character(19, "Cersei Lannister", "Queen of Iron Throne", "Lena Headey", "Female", "Lannister", R.drawable.cersei,"Queen Cersei I Lannister was the twentieth ruler of the Seven Kingdoms and the widow of King Robert Baratheon. She was the daughter of Lord Tywin Lannister, twin sister of Jaime Lannister and elder sister of Tyrion Lannister. She was involved in an incestuous relationship with Jaime, who was secretly the father of her three bastard children, Joffrey, Myrcella and Tommen. After all her children died, Cersei assumed the throne, making her the first officially recognized queen regnant in the history of the Seven Kingdoms. Her reign came to an abrupt end during the Battle of King's Landing, where she and Jaime were killed. She was the last monarch to sit on the Iron Throne."),
        Character(20, "Tyrion Lannister", "The Imp", "Peter Dinklage", "Male", "Lannister", R.drawable.tyrion,"Tyrion's mother, Joanna Lannister, died giving birth to him, a tragedy which Tywin and Cersei unfairly blame Tyrion for.[1][2] Tyrion is mocked for being a dwarf, called derisive names such as \"Imp\" and \"Halfman\", which he tries to embrace to keep his self esteem up. Had an infant with dwarfism like Tyrion been born a commoner, he'd have been left in the woods to die; luckily, his birthright as a Lannister afforded him significant wealth and power.[3] When Tyrion was sixteen, he interrupted the attempted rape of a wheelwright's daughter. While Jaime dispatched the attackers, Tyrion helped the girl, named Tysha, recover. They later became lovers and got married in secret."),

    )
}